### ISSUE TITLE
fftw install problem on Linux Debian stable (10) 

### ISSUE THREAD

**Issue by paulauvirage** [olafmersmann/fftw#1]
Hello

I am trying to install fftw, as a required dependencyy for warbleR, and failing to install fftw with the following message:

/usr/bin/ld: final link failed: nonrepresentable section on output
collect2: error: ld returned 1 exit status
make: *** [/usr/share/R/share/make/shlib.mk:6: fftw.so] Error 1
ERROR: compilation failed for package ‘fftw’

Prior to that, the console repeatedly prints `fftw_an_INT_guaranteed_to_be_zero can not be used when making a shared object; recompile with -fPIC` after each line that is run.

I have checked that the package FFTW3 is in the path of fftw. I have also tried to install htorugh the command line and R Studio, both with the same error messages. 

Apologies if this is a problem with my Debian installation rather than fftw, but is there any advice you can give me?

Many thanks

Paul

**Comment by olafmersmann** [comment]
Sorry, can't really help you with that.
